version: '3.7'

services:   
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    environment:
      RABBIT_ADDRESSES: rabbitmq:5672
    ports:
      - 9411:9411
    depends_on:
      - rabbitmq
    networks:
      - currency-network
      
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    mem_limit: 300m
    ports:
      - "5672:5672"
      - 15672:15672
    networks:
      - currency-network
      
networks:
  currency-network: