version: '3.7'

services:
  currency-exchange:
    image: manulc/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    environment:
      # Otra opción es poner "EUREKA.CLIENT.SERVICEURL.DEFAULTZONE" o "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE"
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka
      # Otra opción es poner "SPRING.ZIPKIN.BASEURL" o "SPRING_ZIPKIN_BASEURL"
      - spring.zipkin.baseUrl=http://zipkin-server:9411/
      # Otra opción es poner "SPRING.RABBITMQ.HOST" o "SPRING_RABBITMQ_HOST"
      - spring.rabbitmq.host=rabbitmq
      # Otra opción es poner "SPRING.ZIPKIN.SENDER.TYPE" o "SPRING_ZIPKIN_SENDER_TYPE"
      - spring.zipkin.sender.type=rabbit
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - rabbitmq
    networks:
      - currency-network
      
  currency-conversion:
    image: manulc/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    environment:
      # Otra opción es poner "EUREKA.CLIENT.SERVICEURL.DEFAULTZONE" o "eureka.client.serviceUrl.defaultZone"
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
      # Otra opción es poner "SPRING.ZIPKIN.BASEURL" o "spring.zipkin.baseUrl"
      - SPRING_ZIPKIN_BASEURL=http://zipkin-server:9411/
      # Otra opción es poner "SPRING.RABBITMQ.HOST" o "spring.rabbitmq.host"
      - SPRING_RABBITMQ_HOST=rabbitmq
      # Otra opción es poner "SPRING.ZIPKIN.SENDER.TYPE" o "spring.zipkin.sender"
      - SPRING_ZIPKIN_SENDER_TYPE=rabbit
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - rabbitmq
    networks:
      - currency-network
    
  naming-server:
    image: manulc/mmv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network
  
  api-gateway:
    image: manulc/mmv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    environment:
      # Otra opción es poner "eureka.client.serviceUrl.defaultZone" o "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE"
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      # Otra opción es poner "spring.zipkin.baseUrl" o "SPRING_ZIPKIN_BASEURL"
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      # Otra opción es poner "spring.rabbitmq.host" o "SPRING_RABBITMQ_HOST"
      SPRING.RABBITMQ.HOST: rabbitmq
      # Otra opción es poner "spring.zipkin.sender" o "SPRING_ZIPKIN_SENDER_TYPE"
      SPRING.ZIPKIN.SENDER.TYPE: rabbit
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
      - rabbitmq
      - currency-exchange
      - currency-conversion
    networks:
      - currency-network
      
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    environment:
      RABBIT_ADDRESSES: rabbitmq:5672
    ports:
      - 9411:9411
    depends_on:
      - rabbitmq
    networks:
      - currency-network
      
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    mem_limit: 300m
    ports:
      - "5672:5672"
      - 15672:15672
    networks:
      - currency-network
      
networks:
  currency-network: